### ISSUE TITLE
都城verのapiを作成する

### ISSUE THREAD

**Issue by kamekyame** [kakomimasu/server#160]
https://procon30resources.s3-ap-northeast-1.amazonaws.com/index.html

**Comment by ninja03** [comment]
/matches/{id}/action
bodyパラメータのactionsのtypeにputが追加

**Comment by ninja03** [comment]
ゲームIDをstringに
https://github.com/kakomimasu/viewer/commit/df73aca197d4d0cfdb4319427bc4d45627fdd609

**Comment by kamekyame** [comment]
Fix #192
